# -*- coding: utf-8 -*-
"""Derive ONFLY's copies of five SoftFloat 3e primitives (D-114).

VL-27: five of Release 3e's thirteen over-length externals are written
`#ifndef <name>` in both include/primitives.h and their own s_*.c.  That is
upstream's extension point, not an accident -- defining the name says "this
platform supplies the primitive" and upstream omits both its declaration
and its definition.  A `#define` meant as a rename therefore deletes them.

D-114 uses the extension point as designed: the macro in
generated/onf3enm.h expands to a call of an ONFLY-owned function, and this
script writes those functions by copying upstream's own body under the new
name.  D-35 already does exactly this for roundPackToF64 and subMagsF64.

WHAT IS COPIED, AND WHAT IS NOT
-------------------------------
Only the body is copied, verbatim.  The single change is the identifier in
the definition line, and it is made by replacing an exact string that the
script first asserts is present -- so if upstream ever changes a signature
this fails rather than silently emitting something that no longer matches.

Nothing under third_party/ is edited; it stays byte-identical to the
released archive (D-28, D-35).  What this produces is a derived work in
ONFLY's own tree, which is what the manifest records.

THE PROOF THAT IT IS RIGHT
--------------------------
Not this script.  A copied body can still be wired up wrongly -- the wrong
macro, the wrong argument order, a missing prototype.  What proves it is
that after the swap the x86 suite still passes: TT-02's TestFloat vectors,
the 2426 fp vectors on both backends, cmpback's bit-for-bit comparison and
the ACC-5 golden fingerprints.  Those fingerprints were computed before any
of this existed, so if a primitive changed behaviour they would move.

THE LICENCE TEXT
----------------
The generated file reproduces third_party/SoftFloat-3e/COPYING.txt in
full, read from that file at generation time rather than retyped, because
the licence's first condition asks every redistribution of source to
retain the conditions and the disclaimer, not a pointer to them (P-41 C7,
D-531).  It is a comment: the object file does not change.

Output: softfloat/onfprim.c.  Never edit by hand (IR-COM-01).

Run:  python softfloat/derive3e.py [--check]
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "third_party", "SoftFloat-3e", "source")
OUT = os.path.join(ROOT, "softfloat", "onfprim.c")
COPYING = os.path.join(ROOT, "third_party", "SoftFloat-3e", "COPYING.txt")

# (upstream file, guarded name, new name)
PRIMS = [
    ("s_countLeadingZeros32.c", "softfloat_countLeadingZeros32", "SFCLZ32"),
    ("s_countLeadingZeros64.c", "softfloat_countLeadingZeros64", "SFCLZ64"),
    ("s_mul64To128M.c", "softfloat_mul64To128M", "SFMUL128"),
    ("s_shiftRightJam64.c", "softfloat_shiftRightJam64", "SFSRJ64"),
    ("s_shortShiftRightJam64.c", "softfloat_shortShiftRightJam64",
     "SFSSRJ64"),
]

HEADER = """\
/*
 * onfprim.c - five SoftFloat 3e primitives under C-04 compliant names.
 *
 * GENERATED by softfloat/derive3e.py.  Do not edit by hand (IR-COM-01).
 *
 * Each body below is upstream's own, copied verbatim; the only change is
 * the identifier in the definition line.  They live here because C-04
 * allows external names of at most eight characters and upstream's are
 * far longer, and because these five cannot be renamed by a macro: each
 * is written `#ifndef <name>` in include/primitives.h and in its own
 * s_*.c, so defining the name omits upstream's definition rather than
 * renaming it (VL-27).  generated/onf3enm.h defines the macro that routes
 * callers here, which is upstream's documented extension point used as
 * intended.
 *
 * third_party/ is untouched and stays byte-identical to the released
 * archive (D-28, D-35).  Berkeley SoftFloat Release 3e is by John R.
 * Hauser, copyright 2011-2018 The Regents of the University of
 * California, three-clause BSD; the full text follows this comment,
 * reproduced from third_party/SoftFloat-3e/COPYING.txt.
 *
 * That these copies behave identically is not proven by copying them.  It
 * is proven by the x86 suite still passing afterwards -- in particular by
 * the ACC-5 golden fingerprints, which were computed before any of this
 * existed and would move if a primitive changed.
 */
"""

PRELUDE = """\

#include <stdint.h>
#include "platform.h"

/*
 * The renames come before primitives.h so its own #ifndef guards see the
 * five as supplied and skip their declarations, which would otherwise
 * clash with the definitions below.  primitives.h is still needed: these
 * bodies reference other primitives, notably the countLeadingZeros8
 * table.
 */
#include "onf3enm.h"
#include "primitiveTypes.h"
#include "primitives.h"
"""


def body_of(filename, guarded, newname):
    path = os.path.join(SRC, filename)
    text = io.open(path, encoding="latin-1").read()

    marker = "#ifndef %s" % guarded
    if marker not in text:
        raise SystemExit("derive3e: %s no longer contains %r; upstream has "
                         "changed and this script must be revisited"
                         % (filename, marker))
    after = text.split(marker, 1)[1]
    end = after.rfind("#endif")
    if end < 0:
        raise SystemExit("derive3e: no #endif closing the guard in %s"
                         % filename)
    block = after[:end]

    # Drop upstream's own includes: this file supplies them once at the
    # top, in an order that puts the renames in place first.
    #
    # Drop upstream's self-define too.  Three of these files carry
    #     #define softfloat_countLeadingZeros32 softfloat_countLeadingZeros32
    # just before including primitives.h, which is how upstream stops that
    # header emitting an inline copy beside the real one.  onf3enm.h now
    # defines the same name to something else, so keeping this line would
    # redefine it back and undo the rename.
    keep = []
    for ln in block.splitlines():
        t = ln.strip()
        if t.startswith("#include"):
            continue
        if t.startswith("#define") and t.split()[1:2] == [guarded]:
            continue
        keep.append(ln)
    block = "\n".join(keep)

    # The definition line, renamed.  The exact spelling is asserted rather
    # than pattern-matched loosely, so a changed signature stops the build.
    pat = re.compile(r"^([A-Za-z_][A-Za-z0-9_ \*]*?)\s+%s\s*\("
                     % re.escape(guarded), re.M)
    if not pat.search(block):
        raise SystemExit("derive3e: no definition of %s found in %s"
                         % (guarded, filename))
    block = pat.sub(lambda m: "%s %s(" % (m.group(1), newname), block, 1)

    if guarded in block:
        raise SystemExit("derive3e: %s still appears in the derived body "
                         "of %s" % (guarded, filename))
    return block.strip("\n")


def licence():
    """Upstream's COPYING.txt, from its copyright line on, as a comment."""
    text = io.open(COPYING, encoding="ascii").read()
    start = text.find("Copyright ")
    if start < 0 or "*/" in text:
        raise SystemExit("derive3e: %s has changed shape; revisit" % COPYING)
    body = text[start:].rstrip("\n")
    return ("/*" + "=" * 76 + "\n\n"
            "Berkeley SoftFloat Release 3e's licence, reproduced from\n"
            "third_party/SoftFloat-3e/COPYING.txt as its first condition "
            "requires.\n\n"
            + body + "\n\n" + "=" * 77 + "*/\n")


def render():
    parts = [HEADER + licence() + PRELUDE]
    for filename, guarded, newname in PRIMS:
        parts.append("")
        parts.append("/* ---- from %s: %s ---- */" % (filename, guarded))
        parts.append(body_of(filename, guarded, newname))
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def main(argv):
    text = render()
    for n, line in enumerate(text.splitlines(), 1):
        if len(line) > 80:
            raise SystemExit("derive3e: line %d is %d columns" % (n, len(line)))
    if "--check" in argv:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != text:
            sys.stderr.write("derive3e: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("derive3e: %s matches upstream's bodies\n" % OUT)
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(text)
    sys.stdout.write("derive3e: wrote %s, %d primitives\n"
                     % (OUT, len(PRIMS)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
