# -*- coding: utf-8 -*-
"""Derive ONFLY's flags-free SoftFloat files from the pristine upstream source.

D-34 requires the soft backend to hold no writable static data, and D-35 chose
ONFLY-owned derived copies over patching third_party/, so that the vendored tree
keeps matching the SHA-256 digests recorded in D-28.

Most of that is achieved without touching source at all: softfloat/onfflag.c
supplies a no-op softfloat_raiseFlags and the specialization's own version is
not compiled.  What remains are the reads of SoftFloat's global rounding mode.

This script performs those edits mechanically rather than by hand.  Each
substitution asserts that its target text occurs exactly once, so an upstream
change silently altering the meaning of a patch is impossible: the derivation
fails instead.  The output carries a DO-NOT-EDIT banner and the SHA-256 of the
upstream file it came from.

softfloat/onfrpk.c is NOT produced here.  That one required removing dead code
(the isTiny computation) and restructuring control flow, which is a reading of
the algorithm rather than a textual substitution, so it is a reviewed hand
derivation with its reasoning written out in the file itself.

Run:  python softfloat/derive.py
"""
import hashlib
import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
UPSTREAM = os.path.join(ROOT, "third_party", "SoftFloat-3e", "source")

BANNER = """/*
 * %(out)s - ONFLY derived file - DO NOT EDIT.
 *
 * Generated by softfloat/derive.py from Berkeley SoftFloat Release 3e,
 * source/%(src)s, by John R. Hauser.
 * Copyright 2011-2018 The Regents of the University of California.
 * All rights reserved.  Redistributed and modified under the three-clause BSD
 * licence in third_party/SoftFloat-3e/COPYING.txt (NFR-LIC-01).
 *
 * upstream sha256 %(sha)s
 *
 * Modification applied (D-34, D-35):
%(why)s *
 * Edit softfloat/derive.py and regenerate; hand edits are lost.
 */
"""

DERIVATIONS = [
    {
        "src": "s_subMagsF64.c",
        "out": "onfsub.c",
        "why": (
            " *   The `x - x` sign rule reads SoftFloat's global rounding mode:\n"
            " *     packToF64UI( (softfloat_roundingMode == softfloat_round_min), 0, 0 )\n"
            " *   IEEE 754 makes the difference of two equal finite values +0 in\n"
            " *   every rounding mode except round-toward-negative-infinity, where\n"
            " *   it is -0.  NR-01 fixes the mode to round-to-nearest-ties-to-even\n"
            " *   and NR-10 forbids ever changing it, so that comparison is false\n"
            " *   by construction and is replaced by the constant 0.  The result is\n"
            " *   unchanged: x - x is +0.  The global read, and with it the last\n"
            " *   writable static datum in the binary64 path, disappears.\n"
        ),
        "subs": [
            ("(softfloat_roundingMode == softfloat_round_min)",
             "0 /* ONFLY: round-to-nearest-even fixed by NR-01/NR-10 */"),
        ],
    },
]


def derive(spec):
    src_path = os.path.join(UPSTREAM, spec["src"])
    raw = io.open(src_path, "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    # Read again in universal-newline mode so the text is LF regardless of what
    # upstream ships.  SoftFloat 3e ships CRLF; carrying that through would make
    # the generated file churn against git's eol=lf normalisation on every
    # regeneration, showing up as a spurious modification.  The digest above is
    # taken from the raw bytes, so it still identifies the true upstream file.
    text = io.open(src_path, "r", encoding="utf-8",
                   errors="replace", newline=None).read()

    for old, new in spec["subs"]:
        count = text.count(old)
        assert count == 1, (
            "%s: expected exactly 1 occurrence of %r, found %d. Upstream has "
            "changed; review the derivation before regenerating."
            % (spec["src"], old, count))
        text = text.replace(old, new)

    banner = BANNER % {"out": spec["out"], "src": spec["src"],
                       "sha": sha, "why": spec["why"]}
    out_path = os.path.join(HERE, spec["out"])
    io.open(out_path, "w", encoding="utf-8", newline="\n").write(banner + text)
    print("derived %-12s from %-18s upstream sha256 %s"
          % (spec["out"], spec["src"], sha[:16] + "..."))


def main():
    for spec in DERIVATIONS:
        derive(spec)


if __name__ == "__main__":
    main()
