/*
 * onfprim.c - five SoftFloat 3e primitives under C-04 compliant names.
 *
 * GENERATED by softfloat/derive3e.py.  Do not edit by hand (IR-COM-01).
 *
 * Each body below is upstream's own, copied verbatim; the only change is
 * the identifier in the definition line.  They live here because C-04
 * allows external names of at most eight characters and upstream's are
 * far longer, and because these five cannot be renamed by a macro: each
 * is written `#ifndef <name>` in include/primitives.h and in its own
 * s_*.c, so defining the name omits upstream's definition rather than
 * renaming it (VL-27).  generated/onf3enm.h defines the macro that routes
 * callers here, which is upstream's documented extension point used as
 * intended.
 *
 * third_party/ is untouched and stays byte-identical to the released
 * archive (D-28, D-35).  Berkeley SoftFloat Release 3e is by John R.
 * Hauser, copyright 2011-2018 The Regents of the University of
 * California, three-clause BSD; the full text is in
 * third_party/SoftFloat-3e/COPYING.txt.
 *
 * That these copies behave identically is not proven by copying them.  It
 * is proven by the x86 suite still passing afterwards -- in particular by
 * the ACC-5 golden fingerprints, which were computed before any of this
 * existed and would move if a primitive changed.
 */
#include <stdint.h>
#include "platform.h"

/*
 * The renames come before primitives.h so its own #ifndef guards see the
 * five as supplied and skip their declarations, which would otherwise
 * clash with the definitions below.  primitives.h is still needed: these
 * bodies reference other primitives, notably the countLeadingZeros8
 * table.
 */
#include "onf3enm.h"
#include "primitiveTypes.h"
#include "primitives.h"


/* ---- from s_countLeadingZeros32.c: softfloat_countLeadingZeros32 ---- */
uint_fast8_t SFCLZ32( uint32_t a )
{
    uint_fast8_t count;

    count = 0;
    if ( a < 0x10000 ) {
        count = 16;
        a <<= 16;
    }
    if ( a < 0x1000000 ) {
        count += 8;
        a <<= 8;
    }
    count += softfloat_countLeadingZeros8[a>>24];
    return count;

}


/* ---- from s_countLeadingZeros64.c: softfloat_countLeadingZeros64 ---- */
uint_fast8_t SFCLZ64( uint64_t a )
{
    uint_fast8_t count;
    uint32_t a32;

    count = 0;
    a32 = a>>32;
    if ( ! a32 ) {
        count = 32;
        a32 = a;
    }
    /*------------------------------------------------------------------------
    | From here, result is current count + count leading zeros of `a32'.
    *------------------------------------------------------------------------*/
    if ( a32 < 0x10000 ) {
        count += 16;
        a32 <<= 16;
    }
    if ( a32 < 0x1000000 ) {
        count += 8;
        a32 <<= 8;
    }
    count += softfloat_countLeadingZeros8[a32>>24];
    return count;

}


/* ---- from s_mul64To128M.c: softfloat_mul64To128M ---- */
void SFMUL128( uint64_t a, uint64_t b, uint32_t *zPtr )
{
    uint32_t a32, a0, b32, b0;
    uint64_t z0, mid1, z64, mid;

    a32 = a>>32;
    a0 = a;
    b32 = b>>32;
    b0 = b;
    z0 = (uint64_t) a0 * b0;
    mid1 = (uint64_t) a32 * b0;
    mid = mid1 + (uint64_t) a0 * b32;
    z64 = (uint64_t) a32 * b32;
    z64 += (uint64_t) (mid < mid1)<<32 | mid>>32;
    mid <<= 32;
    z0 += mid;
    zPtr[indexWord( 4, 1 )] = z0>>32;
    zPtr[indexWord( 4, 0 )] = z0;
    z64 += (z0 < mid);
    zPtr[indexWord( 4, 3 )] = z64>>32;
    zPtr[indexWord( 4, 2 )] = z64;

}


/* ---- from s_shiftRightJam64.c: softfloat_shiftRightJam64 ---- */
uint64_t SFSRJ64( uint64_t a, uint_fast32_t dist )
{

    return
        (dist < 63) ? a>>dist | ((uint64_t) (a<<(-dist & 63)) != 0) : (a != 0);

}


/* ---- from s_shortShiftRightJam64.c: softfloat_shortShiftRightJam64 ---- */
uint64_t SFSSRJ64( uint64_t a, uint_fast8_t dist )
{

    return a>>dist | ((a & (((uint_fast64_t) 1<<dist) - 1)) != 0);

}
