# -*- coding: utf-8 -*-
"""Generate the COBOL copybook, C header/source and Python accessors.

IR-COM-01 / D-18: every artifact this script writes carries a DO-NOT-EDIT
banner and the SHA-256 of layout/master.py, so a hand edit or a stale
regeneration is visible by inspection.

Run:  python layout/generate.py
"""
import hashlib
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import master as M  # noqa: E402

MASTER_SHA = hashlib.sha256(
    io.open(os.path.join(HERE, "master.py"), "rb").read()).hexdigest()
OUTDIR = os.path.join(ROOT, "generated")

COBOL_PIC = {"i16": "PIC S9(4) COMP", "i32": "PIC S9(9) COMP"}
PY_CODE = {"i16": "h", "i32": "i"}

BANNER = [
    "ONFLY generated file - DO NOT EDIT (IR-COM-01, D-18).",
    "Generated by layout/generate.py from layout/master.py.",
    # The digest goes on its own line: prefixed with " * " it would otherwise
    # reach 84 columns, and D-93 holds generated source to 80 because the TK5
    # card reader discards the excess without saying so.
    "master.py sha256",
    "  " + MASTER_SHA,
    "Edit layout/master.py and regenerate.",
    "Hand edits are lost and are a requirements violation.",
]


def pic_of(f):
    if f.kind in ("chr", "byt"):
        return "PIC X(%d)" % f.size
    return COBOL_PIC[f.kind]


def py_code_of(f):
    if f.kind in ("chr", "byt"):
        return "%ds" % f.size
    return PY_CODE[f.kind]


# ---------------------------------------------------------------------------
# COBOL copybook.  MVT COBOL column discipline (C-03): Area A at column 8,
# Area B at column 12, nothing past column 72.  No scope terminators and no
# COMP-5 (IR-COM-02).
# ---------------------------------------------------------------------------
def _cobol_comment(text):
    """Wrap one banner line into COBOL comment lines that end by column 72.

    The prefix '      *' occupies 7 columns, leaving 65 for text.  The SHA-256
    digest alone is 64 hex characters, so wrapping is not optional here.
    """
    prefix = "      *"
    width = 72 - len(prefix)
    out = []
    remaining = text
    while len(remaining) > width:
        cut = remaining.rfind(" ", 0, width + 1)
        if cut <= 0:
            cut = width          # an unbroken token such as the digest
        out.append(prefix + remaining[:cut].rstrip())
        remaining = remaining[cut:].lstrip() if remaining[cut] == " " else remaining[cut:]
    out.append(prefix + remaining)
    return out


def gen_cobol():
    lines = []
    for b in BANNER:
        lines.extend(_cobol_comment(b))
    lines.append("      *")
    lines.append("       01  ONF-COMMAREA.")
    for f in M.HEAD:
        lines.append("           05  %-22s %s." % (f.cobol, pic_of(f)))
    lines.append("           05  ONF-OUT OCCURS %d TIMES." % M.MAX_OUT)
    for f in M.OUT:
        lines.append("               10  %-18s %s." % (f.cobol, pic_of(f)))
    for n, line in enumerate(lines, 1):
        assert len(line) <= 72, "copybook line %d past column 72: %r" % (n, line)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# C header.  C89 + long long only (NR-04), no float/double (NR-05), external
# names at most 8 characters (C-04), field access by explicit byte shift and
# never by a pointer cast over the buffer (FR-LOD-05, IR-COM-04).
# ---------------------------------------------------------------------------
def gen_c_header():
    L = ["/*"]
    L += [" * " + b for b in BANNER]
    L.append(" */")
    L.append("#ifndef ONFCOM_H")
    L.append("#define ONFCOM_H")
    L.append("")
    L.append('#include "onfplat.h"')
    L.append("")
    L.append("/* Record geometry (SRS section 4.3). */")
    L.append("#define ONF_RECLEN   %d" % M.RECORD_LEN)
    L.append("#define ONF_HEADLEN  %d" % M.HEAD_LEN)
    L.append("#define ONF_MAXOUT   %d" % M.MAX_OUT)
    L.append("#define ONF_OUTLEN   %d" % M.OUT_ENTRY_LEN)
    L.append("")
    L.append("/* Absolute offsets of the fixed part. */")
    for f in M.HEAD:
        L.append("#define ONF_O_%-10s %3d   /* %s, %d bytes */"
                 % (f.name.upper(), f.off, f.cobol, f.size))
    L.append("")
    L.append("/* Offsets inside one ONF-OUT entry; entry k begins at")
    L.append("   ONF_HEADLEN + k * ONF_OUTLEN. */")
    for f in M.OUT:
        L.append("#define ONF_OE_%-9s %3d   /* %s, %d bytes */"
                 % (f.name.upper(), f.off, f.cobol, f.size))
    L.append("")
    L.append("/* Declared value ranges (IR-COM-02): each range fits its PIC")
    L.append("   digit count, so the TRUNC option cannot alter a value. */")
    for f in M.HEAD + M.OUT:
        if f.lo is not None:
            L.append("#define ONF_LO_%-9s (%dL)" % (f.name.upper(), f.lo))
            L.append("#define ONF_HI_%-9s (%dL)" % (f.name.upper(), f.hi))
    L.append("")
    L.append("/* Decoded in-memory form.  On a big-endian host with natural")
    L.append("   alignment this maps onto the record exactly (IR-COM-03).  The")
    L.append("   accessors below are used on every host regardless, so no code")
    L.append("   depends on that coincidence. */")
    L.append("struct onfout {")
    L.append("    onf_i32 id;")
    L.append("    onf_i32 latus;")
    L.append("    onf_i16 spikes;")
    L.append("    onf_u8  filler[2];")
    L.append("};")
    L.append("")
    L.append("struct onfcom {")
    L.append("    onf_u8  stimcode[8];")
    L.append("    onf_i32 seed;")
    L.append("    onf_i16 stimrate;")
    L.append("    onf_i16 simms;")
    L.append("    onf_i16 rc;")
    L.append("    onf_i16 outcount;")
    L.append("    onf_u8  fprint[4];")
    L.append("    onf_i32 steps;")
    L.append("    struct onfout out[ONF_MAXOUT];")
    L.append("};")
    L.append("")
    L.append("/* TU-07: size and offset assertions checked at compile time.  A")
    L.append("   negative array dimension is a constraint violation in C89, so a")
    L.append("   layout drift fails the build rather than the run. */")
    # Split across two emitted lines: one line reaches 95 columns, and D-93
    # holds generated source to 80.
    L.append("typedef char onfcom_len_assert[")
    L.append("    (ONF_HEADLEN + ONF_MAXOUT * ONF_OUTLEN == ONF_RECLEN)"
             " ? 1 : -1];")
    L.append("typedef char onfout_len_assert"
             "[(sizeof(struct onfout) == ONF_OUTLEN) ? 1 : -1];")
    L.append("typedef char onfcom_str_assert"
             "[(sizeof(struct onfcom) == ONF_RECLEN) ? 1 : -1];")
    L.append("")
    L.append("/* Big-endian accessors over a raw record buffer (IR-COM-04,")
    L.append("   FR-LOD-05).  External names are 6 characters (C-04). */")
    L.append("onf_i32 onfg32(const onf_u8 *b, onf_i32 off);")
    L.append("onf_i16 onfg16(const onf_u8 *b, onf_i32 off);")
    L.append("void    onfp32(onf_u8 *b, onf_i32 off, onf_i32 v);")
    L.append("void    onfp16(onf_u8 *b, onf_i32 off, onf_i16 v);")
    L.append("")
    L.append("/* Stimulus codes and numeric IDs (FR-BAT-05, IR-COM-05, D-39).")
    L.append("   0 is reserved for an unrecognised code, so a request record")
    L.append("   zeroed by a truncated transfer cannot look like a valid SUGR")
    L.append("   request. */")
    L.append("#define ONF_STIM_UNKNOWN %d" % M.STIM_UNKNOWN)
    for _code, _sid, _note in M.STIM_CODES:
        L.append("#define ONF_STIM_%-6s %d   /* %s */" % (_code, _sid, _note))
    L.append("")
    L.append("#endif /* ONFCOM_H */")
    return "\n".join(L) + "\n"


C_SOURCE_BODY = r'''#include "onfcom.h"

/* Assemble a big-endian unsigned 32-bit value by explicit shifts.  No pointer
   cast is taken over the buffer (FR-LOD-05), so the result depends on neither
   host byte order nor alignment. */
static onf_u32 onfu32g(const onf_u8 *b, onf_i32 o)
{
    onf_u32 v;
    v  = (onf_u32)b[o]     << 24;
    v |= (onf_u32)b[o + 1] << 16;
    v |= (onf_u32)b[o + 2] <<  8;
    v |= (onf_u32)b[o + 3];
    return v;
}

onf_i32 onfg32(const onf_u8 *b, onf_i32 off)
{
    onf_u32 u;
    u = onfu32g(b, off);
    /* Convert to signed without ever relying on signed overflow (NR-11).  For
       u >= 2^31 the form below keeps every intermediate inside the signed
       range: 0xFFFFFFFF - u is at most 0x7FFFFFFF, and negating it then
       subtracting one reaches exactly INT32_MIN without overflowing. */
    if (u <= 0x7FFFFFFFUL) {
        return (onf_i32)u;
    }
    return -(onf_i32)(0xFFFFFFFFUL - u) - 1;
}

onf_i16 onfg16(const onf_u8 *b, onf_i32 off)
{
    onf_u32 u;
    u  = (onf_u32)b[off] << 8;
    u |= (onf_u32)b[off + 1];
    if (u <= 0x7FFFUL) {
        return (onf_i16)u;
    }
    return (onf_i16)(-(onf_i32)(0xFFFFUL - u) - 1);
}

void onfp32(onf_u8 *b, onf_i32 off, onf_i32 v)
{
    onf_u32 u;
    /* Signed to two's complement without signed overflow: for v < 0, -(v+1) is
       always representable even when v is INT32_MIN. */
    if (v < 0) {
        u = 0xFFFFFFFFUL - (onf_u32)(-(v + 1));
    } else {
        u = (onf_u32)v;
    }
    b[off]     = (onf_u8)((u >> 24) & 0xFFUL);
    b[off + 1] = (onf_u8)((u >> 16) & 0xFFUL);
    b[off + 2] = (onf_u8)((u >>  8) & 0xFFUL);
    b[off + 3] = (onf_u8)( u        & 0xFFUL);
}

void onfp16(onf_u8 *b, onf_i32 off, onf_i16 v)
{
    onf_u32 u;
    if (v < 0) {
        u = 0xFFFFUL - (onf_u32)(-((onf_i32)v + 1));
    } else {
        u = (onf_u32)v;
    }
    b[off]     = (onf_u8)((u >> 8) & 0xFFUL);
    b[off + 1] = (onf_u8)( u       & 0xFFUL);
}
'''


def gen_c_source():
    L = ["/*"]
    L += [" * " + b for b in BANNER]
    L.append(" */")
    return "\n".join(L) + "\n" + C_SOURCE_BODY


# ---------------------------------------------------------------------------
# Python accessors for the oracle and the test harness.
# ---------------------------------------------------------------------------
def gen_python():
    head_fmt = ">" + "".join(py_code_of(f) for f in M.HEAD)
    out_fmt = ">" + "".join(py_code_of(f) for f in M.OUT)
    L = ["# -*- coding: utf-8 -*-"]
    L += ["# " + b for b in BANNER]
    L.append("")
    L.append("import struct")
    L.append("")
    L.append("RECORD_LEN = %d" % M.RECORD_LEN)
    L.append("HEAD_LEN   = %d" % M.HEAD_LEN)
    L.append("MAX_OUT    = %d" % M.MAX_OUT)
    L.append("OUT_LEN    = %d" % M.OUT_ENTRY_LEN)
    L.append("")
    L.append("# Big-endian struct formats (IR-COM-04).")
    L.append("HEAD_FMT = %r" % head_fmt)
    L.append("OUT_FMT  = %r" % out_fmt)
    L.append("HEAD_FIELDS = %r" % [f.name for f in M.HEAD])
    L.append("OUT_FIELDS  = %r" % [f.name for f in M.OUT])
    L.append("")
    L.append("assert struct.calcsize(HEAD_FMT) == HEAD_LEN")
    L.append("assert struct.calcsize(OUT_FMT) == OUT_LEN")
    L.append("assert HEAD_LEN + MAX_OUT * OUT_LEN == RECORD_LEN")
    L.append("")
    L.append("# Absolute offsets of the fixed part.")
    L.append("OFF = {")
    for f in M.HEAD:
        L.append("    %r: %d," % (f.name, f.off))
    L.append("}")
    L.append("")
    L.append("# Offsets inside one ONF-OUT entry.")
    L.append("OUT_OFF = {")
    for f in M.OUT:
        L.append("    %r: %d," % (f.name, f.off))
    L.append("}")
    L.append("")
    L.append("# Declared value ranges (IR-COM-02).")
    L.append("RANGES = {")
    for f in M.HEAD + M.OUT:
        if f.lo is not None:
            L.append("    %r: (%d, %d)," % (f.name, f.lo, f.hi))
    L.append("}")
    L.append("")
    L.append("# --- Network file header (IR-NET-01, SRS section 4.1) ---------------")
    L.append("NETHDR_LEN        = %d" % M.NETHDR_LEN)
    L.append("NETHDR_CRC_COVERS = %d" % M.NETHDR_CRC_COVERS)
    L.append("NET_ALIGN         = %d" % M.NET_ALIGN)
    L.append("NET_MAGIC         = 0x%08X" % M.NET_MAGIC)
    L.append("NET_SENTINEL      = 0x%08X" % M.NET_SENTINEL)
    L.append("NET_VMAJOR        = %d" % M.NET_VMAJOR)
    L.append("NET_VMINOR        = %d" % M.NET_VMINOR)
    L.append("")
    L.append("# name -> (kind, offset, size); kind is 'u32', 'u16' or 'f64'.")
    L.append("NETHDR = {")
    for name, kind, off, size in M.NETHDR:
        L.append("    %r: (%r, %d, %d)," % (name, kind, off, size))
    L.append("}")
    L.append("")
    L.append("# Stimulus codes and numeric IDs (FR-BAT-05, IR-COM-05, D-39).")
    L.append("STIM_UNKNOWN = %d" % M.STIM_UNKNOWN)
    L.append("STIM_IDS = {")
    for _code, _sid, _note in M.STIM_CODES:
        L.append("    %r: %d," % (_code, _sid))
    L.append("}")
    L.append("")
    L.append("# Declaration order matters when writing the header.")
    L.append("NETHDR_ORDER = %r" % [f[0] for f in M.NETHDR])
    return "\n".join(L) + "\n"


def gen_net_header():
    """C header for the network file header (IR-NET-01, SRS section 4.1)."""
    L = ["/*"]
    L += [" * " + b for b in BANNER]
    L.append(" */")
    L.append("#ifndef ONFNHD_H")
    L.append("#define ONFNHD_H")
    L.append("")
    L.append('#include "onfplat.h"')
    L.append("")
    L.append("/* Header geometry.  The header CRC at ONF_N_HDRCRC covers bytes")
    L.append("   0 .. ONF_NHDR_CRCLEN-1, i.e. everything before itself")
    L.append("   (IR-NET-07). */")
    L.append("#define ONF_NHDR_LEN     %d" % M.NETHDR_LEN)
    L.append("#define ONF_NHDR_CRCLEN  %d" % M.NETHDR_CRC_COVERS)
    L.append("#define ONF_NET_ALIGN    %d" % M.NET_ALIGN)
    L.append("")
    L.append("/* IR-NET-03: compared as an integer on every platform, never as")
    L.append("   text, so a code-page translation in transport is caught. */")
    L.append("#define ONF_NET_MAGIC    0x%08XUL" % M.NET_MAGIC)
    L.append("/* IR-NET-04: any other decoded value fails with ONF102E. */")
    L.append("#define ONF_NET_SENTINEL 0x%08XUL" % M.NET_SENTINEL)
    L.append("#define ONF_NET_VMAJOR   %d" % M.NET_VMAJOR)
    L.append("#define ONF_NET_VMINOR   %d" % M.NET_VMINOR)
    L.append("")
    L.append("/* Field offsets. */")
    for name, kind, off, size in M.NETHDR:
        L.append("#define ONF_N_%-9s %3d   /* %s, %d bytes */"
                 % (name.upper(), off, kind, size))
    L.append("")
    L.append("typedef char onfnhd_len_assert"
             "[(ONF_N_HDRCRC + 4 == ONF_NHDR_LEN) ? 1 : -1];")
    L.append("typedef char onfnhd_crc_assert"
             "[(ONF_N_HDRCRC == ONF_NHDR_CRCLEN) ? 1 : -1];")
    L.append("")
    L.append("#endif /* ONFNHD_H */")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# COBOL driver with the copybook expanded in place (IR-COM-01, D-161).
#
# Gate G4 measured on TK5 (2026-09-12) that the MVT ANS COBOL compiler
# rejects the standalone COPY statement (IKF1041I-E) and accepts only the
# COBOL-68 form `01 name COPY member.`, which Enterprise COBOL and GnuCOBOL
# refuse.  No single spelling of COPY compiles on both, so IR-COM-01's
# fallback applies: cobol/ONFLYDRV.cbl keeps its COPY ONFCOM. as honest
# COBOL, and this expands that one statement into generated/ONFLYDRV.cbl,
# which is the single source every compiler builds (FR-BAT-03).
# ---------------------------------------------------------------------------
TEMPLATE = os.path.join(ROOT, "cobol", "ONFLYDRV.cbl")
COPY_LINE = re.compile(r"^ {7}COPY ONFCOM\.\s*$")
ANY_COPY = re.compile(r"^ {6}[^*].*\bCOPY\b")


def gen_cobol_driver(copybook):
    src = io.open(TEMPLATE, encoding="ascii").read().splitlines()
    hits = [i for i, l in enumerate(src) if COPY_LINE.match(l)]
    if len(hits) != 1:
        raise SystemExit("cobol/ONFLYDRV.cbl must contain exactly one "
                         "'COPY ONFCOM.' line, found %d" % len(hits))
    stray = [n + 1 for n, l in enumerate(src)
             if ANY_COPY.match(l) and not COPY_LINE.match(l)]
    if stray:
        raise SystemExit("cobol/ONFLYDRV.cbl has a COPY the generator does "
                         "not expand at line(s) %s" % stray)
    i = hits[0]
    head = []
    for b in [
        "ONFLY generated file - DO NOT EDIT (IR-COM-01, D-18, D-161).",
        "Generated by layout/generate.py from cobol/ONFLYDRV.cbl (the",
        "template) and layout/master.py (the layout).",
        "The template's COPY ONFCOM. is expanded below because MVT COBOL",
        "accepts only the COBOL-68 form of COPY (Gate G4, VL-57).",
        BANNER[2], BANNER[3],
        "Edit cobol/ONFLYDRV.cbl or layout/master.py and regenerate.",
        BANNER[5],
    ]:
        head.extend(_cobol_comment(b))
    head.append("      *")
    body = copybook.rstrip("\n").splitlines()
    lines = (head + src[:i]
             + ["      *---- COPY ONFCOM. expanded by layout/generate.py ----"]
             + body
             + ["      *---- end of ONFCOM ----------------------------------"]
             + src[i + 1:])
    for n, line in enumerate(lines, 1):
        assert len(line) <= 72, "driver line %d past column 72: %r" % (n, line)
    return "\n".join(lines) + "\n"


def main():
    if not os.path.isdir(OUTDIR):
        os.makedirs(OUTDIR)
    copybook = gen_cobol()
    artifacts = [
        ("ONFCOM.cpy", copybook),
        ("ONFLYDRV.cbl", gen_cobol_driver(copybook)),
        ("onfcom.h", gen_c_header()),
        ("onfcom.c", gen_c_source()),
        ("onfcom_py.py", gen_python()),
        ("onfnhd.h", gen_net_header()),
    ]
    for name, text in artifacts:
        path = os.path.join(OUTDIR, name)
        io.open(path, "w", encoding="utf-8", newline="\n").write(text)
        print("generated %-14s %5d bytes" % (name, len(text.encode("utf-8"))))
    print("master.py sha256 %s" % MASTER_SHA)


if __name__ == "__main__":
    main()
