# -*- coding: utf-8 -*-
"""Populate and verify a checkout's network fixtures (D-249).

WHY THIS EXISTS
---------------
`data/networks/*.bin` is gitignored -- the four networks total about 322
MB, and their digests are committed in `data/networks/MANIFEST.json`
instead.  A fresh clone or a fresh worktree therefore starts without
them, and nothing in the build says so until a test fails for a reason
that does not name the cause.

Measured, in the Gate G0 session of 2026-09-14: this worktree held a
single `onfnet-malecns-v1.0-path.bin` at its **v1.0** size, 885,416
bytes, where the manifest records v1.1 at 951,200; `srext`, the network
the MVP actually ships, was absent entirely.  `mingw32-make test` ran for
94 seconds and then failed inside `tests/run_req.py` with

    netread.NetworkFileError: ONF103E UNSUPPORTED FORMAT VERSION

which is the engine correctly rejecting a stale file, reported four call
frames away from anything that mentions fixtures.  The fix for the stale
file is not interesting; the fix for the *diagnosis* is this module.

THE RULE THIS FOLLOWS: NEVER TRUST A FILENAME
---------------------------------------------
A fixture is accepted only if its byte count, its CRC-32 and -- when the
manifest carries one -- its SHA-256 all match.  That matters more here
than it looks: the stale file above had exactly the right *name*, in
exactly the right *place*, and was wrong.  Every candidate is verified
before it is linked, and every linked file is verified again afterwards.

WHERE FIXTURES COME FROM
------------------------
In order: `$ONFLY_FIXTURES`, the main checkout this worktree belongs to,
then any sibling worktree.  Nothing outside the project tree is searched
and nothing is ever written outside `data/networks/`.

Files are COPIED, never hard linked by default.  Linking looks free --
322 MB saved per worktree, and the files are nominally immutable -- and
it has already cost this project real damage: on 2026-09-13 the networks
were hard linked between worktrees to save that space, and
`prep/extract.py --refixture` then wrote THROUGH the links, silently
replacing six network files belonging to a different worktree.  A fixture
is immutable only until some tool decides to re-emit it.  `--link` opts
back in for a caller who knows their tree is read-only.

If a network is found nowhere, that is reported as what it is -- a file
that must be regenerated by `prep/emit.py` from the MaleCNS data -- and
not as a link failure.

Run:
    python tools/fixtures.py            copy in what is missing, verify all
    python tools/fixtures.py --check    verify only, change nothing
    python tools/fixtures.py --link     hard link instead of copying -- see
                                        place(), and be sure you mean it
Exit status 0 when every network in the manifest is present and correct.
"""
import io
import json
import os
import shutil
import sys
import zlib

try:
    import hashlib
except ImportError:                                          # pragma: no cover
    hashlib = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NETDIR = os.path.join(ROOT, "data", "networks")
MANIFEST = os.path.join(NETDIR, "MANIFEST.json")


#: Read size for digests().  Any value works; 8 MiB simply keeps the
#: number of system calls small without holding much.
CHUNK = 8 << 20


def digests(path):
    """(bytes, CRC-32 as 8 hex digits, SHA-256 hex) for one file.

    Streamed rather than read whole.  This used to be
    `io.open(path, "rb").read()`, which cannot verify the largest file
    this module's own manifest describes: the MaleCNS connectome weights
    are 1,051,241,946 bytes and a single read of that size fails on
    Windows with `OSError: [Errno 22] Invalid argument` -- an error that
    names neither the file nor its size, and which surfaced four frames
    inside `matches()`.

    Chunking also means the check no longer needs a gigabyte of resident
    memory to decide whether a gigabyte on disk is the right gigabyte.
    Both digests are incremental, so the result is identical to what the
    whole-file version returned.
    """
    size, crc, sha = 0, 0, hashlib.sha256() if hashlib else None
    with io.open(path, "rb") as fh:
        while True:
            block = fh.read(CHUNK)
            if not block:
                break
            size += len(block)
            crc = zlib.crc32(block, crc)
            if sha is not None:
                sha.update(block)
    return size, "%08X" % (crc & 0xFFFFFFFF), sha.hexdigest() if sha else ""


def matches(path, want):
    """True when `path` is the file the manifest describes.

    All three checks, not the cheap one alone: the defect this module
    exists for was a file of the right name whose size was wrong, and a
    file of the right size whose contents were wrong would be worse.
    """
    if not os.path.exists(path):
        return False, "absent"
    size, crc, sha = digests(path)
    if size != want["bytes"]:
        return False, "%d bytes, expected %d" % (size, want["bytes"])
    if crc != want["crc32"]:
        return False, "CRC %s, expected %s" % (crc, want["crc32"])
    exp = want.get("sha256")
    if exp and sha and sha != exp:
        return False, "SHA-256 %s..., expected %s..." % (sha[:16], exp[:16])
    return True, "%d bytes, CRC %s" % (size, crc)


def search_roots(subdir=os.path.join("data", "networks")):
    """Directories that might hold a good copy, most likely first.

    A worktree lives at <main>/.claude/worktrees/<name>, so the main
    checkout is three levels up.  Its siblings are the other worktrees.
    Nothing outside that tree is considered.

    `subdir` is the path RELATIVE to a checkout root, so the same search
    serves `data/networks` and `data/malecns`.  It defaults to the
    former, which is what every caller before D-269 wanted.
    """
    here = os.path.join(ROOT, subdir)
    roots = []
    env = os.environ.get("ONFLY_FIXTURES")
    if env:
        roots.append(env)
    parts = ROOT.replace("\\", "/").split("/")
    if len(parts) >= 3 and parts[-2] == "worktrees" and parts[-3] == ".claude":
        main = "/".join(parts[:-3])
        roots.append(os.path.join(main, subdir))
        wt = "/".join(parts[:-1])
        if os.path.isdir(wt):
            for name in sorted(os.listdir(wt)):
                cand = os.path.join(wt, name, subdir)
                if os.path.isdir(cand) and os.path.abspath(cand) != \
                        os.path.abspath(here):
                    roots.append(cand)
    return roots


def place(src, dst, link=False):
    """Copy src to dst.  Hard link only when explicitly asked.

    COPY IS THE DEFAULT AND THE DEFAULT IS NOT NEGOTIABLE BY ACCIDENT.
    Hard linking looks free -- 322 MB saved per worktree, and the files
    are nominally immutable -- and it has already cost this project real
    damage once.  On 2026-09-13 the networks were hard linked between
    worktrees to save that space, and `prep/extract.py --refixture` then
    wrote THROUGH the links, silently replacing six network files
    belonging to a different worktree.  Nothing reported it; the files
    simply became something else.

    A fixture is only immutable until some tool decides to re-emit it.
    So the safe default is a real copy, and `--link` exists for the
    caller who knows their tree is read-only and wants the space back.

    `fsutil hardlink list <file>` shows whether a file has more than one
    name, which is how that incident was eventually diagnosed.
    """
    if os.path.exists(dst):
        os.remove(dst)
    if link:
        try:
            os.link(src, dst)
            return "linked"
        except Exception:
            pass
    shutil.copyfile(src, dst)
    return "copied"


CNSDIR = os.path.join(ROOT, "data", "malecns")
CNSMAN = os.path.join(CNSDIR, "MANIFEST.json")


def malecns(keys, check_only=False, link=False):
    """Place named MaleCNS source files, verified like any fixture.

    D-269 needs `prep/names.py` to read per-body cell types, which live
    in the annotations feather -- gitignored, 14.5 MB, and described by
    `data/malecns/MANIFEST.json` with the same bytes/CRC-32/SHA-256
    triple the networks carry.

    Files are named EXPLICITLY and never fetched wholesale.  The third
    file in that manifest, the connectome weights, is **1,051,241,946
    bytes**, and a `--all` that quietly copied it into every worktree
    would be a gigabyte of surprise for a caller who wanted 14 MB.
    """
    if not os.path.exists(CNSMAN):
        sys.stderr.write("fixtures: no manifest at %s\n" % CNSMAN)
        return 1
    man = json.loads(io.open(CNSMAN, encoding="utf-8").read())
    files = man["files"]
    roots = search_roots(os.path.join("data", "malecns"))
    bad = 0
    for key in keys:
        if key not in files:
            sys.stdout.write("fixtures: %-14s UNKNOWN (have %s)\n"
                             % (key, ", ".join(sorted(files))))
            bad += 1
            continue
        want = files[key]
        dst = os.path.join(CNSDIR, want["file"])
        ok, why = matches(dst, want)
        if ok:
            sys.stdout.write("fixtures: %-14s OK       %s\n" % (key, why))
            continue
        if check_only:
            sys.stdout.write("fixtures: %-14s MISSING  %s\n" % (key, why))
            bad += 1
            continue
        found = None
        for r in roots:
            cand = os.path.join(r, want["file"])
            good, _ = matches(cand, want)
            if good:
                found = cand
                break
        if found is None:
            sys.stdout.write(
                "fixtures: %-14s NOT FOUND (%s). Searched %d location(s). "
                "It is downloaded from %s\n"
                % (key, why, len(roots), want.get("url", "the dataset")))
            bad += 1
            continue
        how = place(found, dst, link=link)
        ok, why = matches(dst, want)
        sys.stdout.write("fixtures: %-14s %s   %s  <- %s\n"
                         % (key, how.upper(), why, found)
                         if ok else
                         "fixtures: %-14s FAILED after %s: %s\n"
                         % (key, how, why))
        bad += 0 if ok else 1
    return 1 if bad else 0


def main(argv):
    check_only = "--check" in argv
    link = "--link" in argv

    if "--malecns" in argv:
        i = argv.index("--malecns")
        keys = [a for a in argv[i + 1:] if not a.startswith("--")]
        if not keys:
            keys = ["annotations"]
        return malecns(keys, check_only=check_only, link=link)
    if not os.path.exists(MANIFEST):
        sys.stderr.write("fixtures: no manifest at %s\n" % MANIFEST)
        return 1
    man = json.loads(io.open(MANIFEST, encoding="utf-8").read())
    nets = man["networks"]

    roots = search_roots()
    bad = 0
    for key in sorted(nets):
        want = nets[key]
        dst = os.path.join(NETDIR, want["file"])
        ok, why = matches(dst, want)
        if ok:
            sys.stdout.write("fixtures: %-6s OK       %s\n" % (key, why))
            continue
        if check_only:
            sys.stdout.write("fixtures: %-6s MISSING  %s\n" % (key, why))
            bad += 1
            continue

        found = None
        for r in roots:
            cand = os.path.join(r, want["file"])
            good, _ = matches(cand, want)
            if good:
                found = cand
                break
        if found is None:
            sys.stdout.write(
                "fixtures: %-6s NOT FOUND (%s). Searched %d location(s). "
                "This network is regenerated by prep/emit.py from the "
                "MaleCNS data; it is not recoverable by linking.\n"
                % (key, why, len(roots)))
            bad += 1
            continue
        how = place(found, dst, link=link)
        ok, why = matches(dst, want)
        if ok:
            sys.stdout.write("fixtures: %-6s %s   %s  <- %s\n"
                             % (key, how.upper(), why, found))
        else:
            sys.stdout.write("fixtures: %-6s FAILED after %s: %s\n"
                             % (key, how, why))
            bad += 1

    if bad:
        sys.stdout.write("fixtures: %d network(s) missing or wrong\n" % bad)
        return 1
    sys.stdout.write("fixtures: all %d networks present and verified "
                     "against MANIFEST.json\n" % len(nets))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
