# -*- coding: utf-8 -*-
"""Populate and verify a checkout's network fixtures (D-249).

WHY THIS EXISTS
---------------
`data/networks/*.bin` is gitignored -- the four networks total about 322
MB, and their digests are committed in `data/networks/MANIFEST.json`
instead.  A fresh clone or a fresh worktree therefore starts without
them, and nothing in the build says so until a test fails for a reason
that does not name the cause.

Measured, in the Gate G0 session of 2026-09-14: this worktree held a
single `onfnet-malecns-v1.0-path.bin` at its **v1.0** size, 885,416
bytes, where the manifest records v1.1 at 951,200; `srext`, the network
the MVP actually ships, was absent entirely.  `mingw32-make test` ran for
94 seconds and then failed inside `tests/run_req.py` with

    netread.NetworkFileError: ONF103E UNSUPPORTED FORMAT VERSION

which is the engine correctly rejecting a stale file, reported four call
frames away from anything that mentions fixtures.  The fix for the stale
file is not interesting; the fix for the *diagnosis* is this module.

THE RULE THIS FOLLOWS: NEVER TRUST A FILENAME
---------------------------------------------
A fixture is accepted only if its byte count, its CRC-32 and -- when the
manifest carries one -- its SHA-256 all match.  That matters more here
than it looks: the stale file above had exactly the right *name*, in
exactly the right *place*, and was wrong.  Every candidate is verified
before it is linked, and every linked file is verified again afterwards.

WHERE FIXTURES COME FROM
------------------------
In order: `$ONFLY_FIXTURES`, the main checkout this worktree belongs to,
then any sibling worktree.  Nothing outside the project tree is searched
and nothing is ever written outside `data/networks/`.  Files are hard
linked, so they cost no extra disk and cannot drift; on a filesystem that
refuses a link, they are copied.

If a network is found nowhere, that is reported as what it is -- a file
that must be regenerated by `prep/emit.py` from the MaleCNS data -- and
not as a link failure.

Run:
    python tools/fixtures.py            link what is missing, verify all
    python tools/fixtures.py --check    verify only, change nothing
Exit status 0 when every network in the manifest is present and correct.
"""
import io
import json
import os
import shutil
import sys
import zlib

try:
    import hashlib
except ImportError:                                          # pragma: no cover
    hashlib = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NETDIR = os.path.join(ROOT, "data", "networks")
MANIFEST = os.path.join(NETDIR, "MANIFEST.json")


def digests(path):
    """(bytes, CRC-32 as 8 hex digits, SHA-256 hex) for one file."""
    data = io.open(path, "rb").read()
    crc = "%08X" % (zlib.crc32(data) & 0xFFFFFFFF)
    sha = hashlib.sha256(data).hexdigest() if hashlib else ""
    return len(data), crc, sha


def matches(path, want):
    """True when `path` is the file the manifest describes.

    All three checks, not the cheap one alone: the defect this module
    exists for was a file of the right name whose size was wrong, and a
    file of the right size whose contents were wrong would be worse.
    """
    if not os.path.exists(path):
        return False, "absent"
    size, crc, sha = digests(path)
    if size != want["bytes"]:
        return False, "%d bytes, expected %d" % (size, want["bytes"])
    if crc != want["crc32"]:
        return False, "CRC %s, expected %s" % (crc, want["crc32"])
    exp = want.get("sha256")
    if exp and sha and sha != exp:
        return False, "SHA-256 %s..., expected %s..." % (sha[:16], exp[:16])
    return True, "%d bytes, CRC %s" % (size, crc)


def search_roots():
    """Directories that might hold a good copy, most likely first.

    A worktree lives at <main>/.claude/worktrees/<name>, so the main
    checkout is three levels up.  Its siblings are the other worktrees.
    Nothing outside that tree is considered.
    """
    roots = []
    env = os.environ.get("ONFLY_FIXTURES")
    if env:
        roots.append(env)
    parts = ROOT.replace("\\", "/").split("/")
    if len(parts) >= 3 and parts[-2] == "worktrees" and parts[-3] == ".claude":
        main = "/".join(parts[:-3])
        roots.append(os.path.join(main, "data", "networks"))
        wt = "/".join(parts[:-1])
        if os.path.isdir(wt):
            for name in sorted(os.listdir(wt)):
                cand = os.path.join(wt, name, "data", "networks")
                if os.path.isdir(cand) and os.path.abspath(cand) != \
                        os.path.abspath(NETDIR):
                    roots.append(cand)
    return roots


def place(src, dst):
    """Hard link src to dst, copying if the filesystem refuses."""
    if os.path.exists(dst):
        os.remove(dst)
    try:
        os.link(src, dst)
        return "linked"
    except Exception:
        shutil.copyfile(src, dst)
        return "copied"


def main(argv):
    check_only = "--check" in argv
    if not os.path.exists(MANIFEST):
        sys.stderr.write("fixtures: no manifest at %s\n" % MANIFEST)
        return 1
    man = json.loads(io.open(MANIFEST, encoding="utf-8").read())
    nets = man["networks"]

    roots = search_roots()
    bad = 0
    for key in sorted(nets):
        want = nets[key]
        dst = os.path.join(NETDIR, want["file"])
        ok, why = matches(dst, want)
        if ok:
            sys.stdout.write("fixtures: %-6s OK       %s\n" % (key, why))
            continue
        if check_only:
            sys.stdout.write("fixtures: %-6s MISSING  %s\n" % (key, why))
            bad += 1
            continue

        found = None
        for r in roots:
            cand = os.path.join(r, want["file"])
            good, _ = matches(cand, want)
            if good:
                found = cand
                break
        if found is None:
            sys.stdout.write(
                "fixtures: %-6s NOT FOUND (%s). Searched %d location(s). "
                "This network is regenerated by prep/emit.py from the "
                "MaleCNS data; it is not recoverable by linking.\n"
                % (key, why, len(roots)))
            bad += 1
            continue
        how = place(found, dst)
        ok, why = matches(dst, want)
        if ok:
            sys.stdout.write("fixtures: %-6s %s   %s  <- %s\n"
                             % (key, how.upper(), why, found))
        else:
            sys.stdout.write("fixtures: %-6s FAILED after %s: %s\n"
                             % (key, how, why))
            bad += 1

    if bad:
        sys.stdout.write("fixtures: %d network(s) missing or wrong\n" % bad)
        return 1
    sys.stdout.write("fixtures: all %d networks present and verified "
                     "against MANIFEST.json\n" % len(nets))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
