# -*- coding: utf-8 -*-
"""Generate C-04 compliant names for SoftFloat 2c's externals (D-111).

VL-25, measured on TK5: 2c's bits32 build COMPILES under GCCMVS and is then
rejected by Assembler XF, repeatedly, with

    IFO196  FLOAT64@ HAS BEEN PREVIOUSLY DEFINED
    IFO196  FLOAT32@ HAS BEEN PREVIOUSLY DEFINED
    IFO196  INT32@TO HAS BEEN PREVIOUSLY DEFINED
    IFO189  INVALID ENTRY OPERAND, LINKAGE CANNOT BE PERFORMED

GCCMVS truncates an external name to eight characters, so of 2c's 42
externals, 38 fall into three colliding groups: eighteen float32_*,
eighteen float64_* and two int32_to_*.  That is C-04 -- "external names at
most 8 characters, unique ignoring case" -- meeting a library that was
never written for it.

Splitting the library across translation units does not help: the
collision is between symbol NAMES, so it would move from the assembler to
the linkage editor and stay a collision.

WHY A MACRO PROLOGUE
--------------------
The renames are additive.  `third_party/` is never edited (D-28, D-35), so
the file the compiler reads is upstream's, preceded by definitions ONFLY
owns.  Anything calling into the library includes the same header, so
caller and callee agree by construction.

The map is STATED, not derived.  A scheme that mechanically abbreviated
would collide again the first time upstream added a name, and it would do
so silently -- the failure class this project keeps having to close.  Each
name below is written out, and the generator refuses to emit a map that is
not C-04 compliant or not one-to-one.

The renames are applied on x86 too, not only on MVS.  A mechanism used
only on the platform that cannot easily be tested is a mechanism nobody
has tested.

Output: generated/onf2cnm.h.  Never edit by hand (IR-COM-01).

Run:  python tools/gen2cnm.py [--check]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "generated", "onf2cnm.h")

# Operation suffix -> abbreviation.  Kept short enough that "F64" or "F32"
# in front still leaves eight characters or fewer.
SUFFIX = [
    ("add", "ADD"), ("sub", "SUB"), ("mul", "MUL"), ("div", "DIV"),
    ("rem", "REM"), ("sqrt", "SQRT"), ("eq", "EQ"), ("le", "LE"),
    ("lt", "LT"), ("eq_signaling", "EQS"), ("le_quiet", "LEQ"),
    ("lt_quiet", "LTQ"), ("is_nan", "NAN"), ("is_signaling_nan", "SNAN"),
    ("round_to_int", "RTI"), ("to_int32", "TOI32"),
    ("to_int32_round_to_zero", "TOIZ"),
]

# The four externals that are not float32_/float64_/int32_to_.  All are
# over eight characters even though none of them collides, and C-04 is a
# length rule as well as a uniqueness rule.
OTHER = [
    ("float_raise", "FRAISE"),
    ("float_rounding_mode", "FRNDMODE"),
    ("float_detect_tininess", "FTININES"),
    ("float_exception_flags", "FEXCFLAG"),
]


def build():
    pairs = []
    for width, short in (("float32", "F32"), ("float64", "F64")):
        for suffix, abbrev in SUFFIX:
            pairs.append(("%s_%s" % (width, suffix), short + abbrev))
        other = "float64" if width == "float32" else "float32"
        pairs.append(("%s_to_%s" % (width, other),
                      "%sTO%s" % (short, "F64" if width == "float32"
                                  else "F32")))
    pairs.append(("int32_to_float32", "I32TOF32"))
    pairs.append(("int32_to_float64", "I32TOF64"))
    pairs.extend(OTHER)
    return pairs


def verify(pairs):
    """C-04 by construction: at most 8 characters, unique ignoring case."""
    seen = {}
    for old, new in pairs:
        if len(new) > 8:
            raise SystemExit("gen2cnm: %r is %d characters, over C-04's 8"
                             % (new, len(new)))
        key = new.upper()
        if key in seen:
            raise SystemExit("gen2cnm: %r and %r both give %r (C-04 "
                             "requires uniqueness ignoring case)"
                             % (seen[key], old, new))
        seen[key] = old
    olds = [o for o, _ in pairs]
    if len(set(olds)) != len(olds):
        raise SystemExit("gen2cnm: an upstream name is mapped twice")


BANNER = """\
/*
 * onf2cnm.h - C-04 compliant names for SoftFloat 2c (D-111).
 *
 * GENERATED by tools/gen2cnm.py.  Do not edit by hand (IR-COM-01).
 *
 * C-04 requires external names of at most eight characters, unique
 * ignoring case.  SoftFloat 2c exports 42 externals of which 38 collide
 * once GCCMVS truncates them: Assembler XF rejects the unit with
 * "IFO196 FLOAT64@ HAS BEEN PREVIOUSLY DEFINED" and its siblings (VL-25).
 *
 * These definitions rename them before upstream's source is read.  The
 * file under third_party/ is untouched and stays byte-identical to the
 * released archive (D-28, D-35); everything a caller and the library see
 * comes from this one header, so they cannot disagree.
 *
 * Applied on every platform, not only MVS, so that the mechanism is
 * exercised by the ordinary x86 suite.
 */
#ifndef ONFLY_ONF2CNM_H
#define ONFLY_ONF2CNM_H
"""


def render(pairs):
    out = [BANNER, ""]
    width = max(len(o) for o, _ in pairs)
    for old, new in pairs:
        out.append("#define %-*s %s" % (width, old, new))
    out.append("")
    out.append("#endif /* ONFLY_ONF2CNM_H */")
    return "\n".join(out) + "\n"


def main(argv):
    pairs = build()
    verify(pairs)
    text = render(pairs)
    for n, line in enumerate(text.splitlines(), 1):
        if len(line) > 80:
            raise SystemExit("gen2cnm: line %d is %d columns" % (n, len(line)))
    if "--check" in argv:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != text:
            sys.stderr.write("gen2cnm: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("gen2cnm: %s matches the generator, %d names\n"
                         % (OUT, len(pairs)))
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(text)
    sys.stdout.write("gen2cnm: wrote %s, %d names renamed\n"
                     % (OUT, len(pairs)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
