# -*- coding: utf-8 -*-
"""Generate TT-01/32's known-answer vectors (D-118, NR-14).

NR-14 exists for risk R-01: a compiler that synthesises integer
arithmetic wrongly.  Its value comes entirely from testing the arithmetic
that actually runs, which is why D-118 amended it to name the width each
platform's engine uses.

On MVS, under NR-03 and D-105, the engine's float backend is SoftFloat 2c
and it uses no 64-bit integer anywhere.  Everything it does is 32-bit:
multiply, divide, modulo, shifts, and add and subtract with the carry and
borrow recovered by comparison, which is how `add64` and `sub64` in 2c's
softfloat-macros build wider arithmetic out of 32-bit pieces.  Those are
the operations here.

WHY CARRY AND BORROW GET THEIR OWN GROUPS
-----------------------------------------
2c never asks the machine for a carry flag.  It writes

    z1 = a1 + b1;  z0 = a0 + b0 + (z1 < a1);

so the carry is a COMPARISON, and if the compiler gets either the wrapping
addition or that comparison wrong the whole float library is wrong in a
way no float test would localise.  ADDC and SUBB below check exactly that
idiom rather than the sum alone.

The expected answers are computed here in Python with explicit masking, so
they are 32-bit by construction rather than by assumption, and they come
from an implementation sharing no code with the one under test.

Values are emitted as plain 32-bit patterns (NR-06); nothing here needs a
64-bit type, which is the property being tested.

Output: generated/onf32v.h.  Never edit by hand (IR-COM-01).

Run:  python tools/gen32v.py [--check]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "generated", "onf32v.h")

M32 = 0xFFFFFFFF

OPS = ["MUL", "DIV", "MOD", "SHL", "SHR", "ADDC", "SUBB", "CMPU", "CMPS"]

# Operands chosen for the boundaries a 32-bit implementation gets wrong:
# zero, one, the sign bit, the halfword boundary where a 16x16 partial
# product carries, all-ones, and a few values with no structure at all.
VALUES = [
    0x00000000, 0x00000001, 0x00000002, 0x0000FFFF, 0x00010000,
    0x00010001, 0x7FFFFFFF, 0x80000000, 0x80000001, 0xFFFFFFFE,
    0xFFFFFFFF, 0x0000FFFE, 0xFFFF0000, 0x12345678, 0x89ABCDEF,
    0xDEADBEEF, 0x0F0F0F0F, 0xF0F0F0F0, 0x55555555, 0xAAAAAAAA,
]

# Comparison result bits, matching softfloat/onfint.c's own encoding so
# the two self-tests report in one vocabulary.
LT, LE, EQ, GT, GE, NE = 1, 2, 4, 8, 16, 32


def to_signed(v):
    return v - (1 << 32) if v & 0x80000000 else v


def compute(op, a, b):
    """Returns (r, extra).  `extra` carries the carry or borrow bit."""
    if op == "MUL":
        return (a * b) & M32, 0
    if op == "DIV":
        return (a // b) & M32, 0
    if op == "MOD":
        return (a % b) & M32, 0
    if op == "SHL":
        return (a << (b & 31)) & M32, 0
    if op == "SHR":
        return (a >> (b & 31)) & M32, 0
    if op == "ADDC":
        z = (a + b) & M32
        return z, 1 if z < a else 0
    if op == "SUBB":
        z = (a - b) & M32
        return z, 1 if a < b else 0
    if op == "CMPU":
        m = 0
        m |= LT if a < b else 0
        m |= LE if a <= b else 0
        m |= EQ if a == b else 0
        m |= GT if a > b else 0
        m |= GE if a >= b else 0
        m |= NE if a != b else 0
        return m, 0
    sa, sb = to_signed(a), to_signed(b)
    m = 0
    m |= LT if sa < sb else 0
    m |= LE if sa <= sb else 0
    m |= EQ if sa == sb else 0
    m |= GT if sa > sb else 0
    m |= GE if sa >= sb else 0
    m |= NE if sa != sb else 0
    return m, 0


def build():
    rows = []
    n = len(VALUES)
    for op in OPS:
        for i, a in enumerate(VALUES):
            for j in (0, 1, 3, 7, 11, 13):
                b = VALUES[(i + j) % n]
                # NR-11: division and modulo are never asked for a zero
                # divisor, and a shift count is masked to 0..31 rather
                # than left to be undefined.
                if op in ("DIV", "MOD") and b == 0:
                    continue
                r, extra = compute(op, a, b)
                rows.append((op, a, b, r, extra))
    return rows


BANNER = """\
/*
 * onf32v.h - TT-01/32 known-answer vectors (D-118, NR-14).
 *
 * GENERATED by tools/gen32v.py.  Do not edit by hand (IR-COM-01).
 *
 * The 32-bit integer self-test.  NR-14 requires one for each width the
 * platform's engine actually uses; under NR-03 and D-105 the MVS engine
 * uses SoftFloat 2c, which has no 64-bit integer anywhere, so 32 bits is
 * the width that matters there.
 *
 * ADDC and SUBB carry the carry and borrow bits separately because 2c
 * recovers them by comparison -- `z = a + b; carry = (z < a);` -- rather
 * than from a machine flag.  A compiler that got either the wrapping
 * arithmetic or that comparison wrong would break the float library in a
 * way no float test would localise.
 *
 * Expected results come from Python with explicit 32-bit masking, so they
 * are 32-bit by construction and share no code with what they check.
 *
 * No 64-bit integer type appears here, which is the point.
 */
#ifndef ONFLY_ONF32V_H
#define ONFLY_ONF32V_H
"""


def render(rows):
    out = [BANNER, ""]
    for i, op in enumerate(OPS):
        out.append("#define ONF32_%-5s %d" % (op, i))
    out.append("")
    out.append("struct onf32v {")
    out.append("    int op;")
    out.append("    unsigned long a;")
    out.append("    unsigned long b;")
    out.append("    unsigned long r;")
    out.append("    int extra;")
    out.append("};")
    out.append("")
    out.append("#define ONF32_NVEC %d" % len(rows))
    out.append("")
    out.append("static const struct onf32v onf32vec[ONF32_NVEC] = {")
    for op, a, b, r, extra in rows:
        out.append("    { ONF32_%-5s 0x%08lXUL, 0x%08lXUL, 0x%08lXUL, %d },"
                   % (op + ",", a, b, r, extra))
    out.append("};")
    out.append("")
    out.append("#endif /* ONFLY_ONF32V_H */")
    return "\n".join(out) + "\n"


def main(argv):
    rows = build()
    text = render(rows)
    for n, line in enumerate(text.splitlines(), 1):
        if len(line) > 80:
            raise SystemExit("gen32v: line %d is %d columns" % (n, len(line)))
    if "--check" in argv:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != text:
            sys.stderr.write("gen32v: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("gen32v: %s matches the generator, %d vectors\n"
                         % (OUT, len(rows)))
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(text)
    counts = {}
    for op, _a, _b, _r, _e in rows:
        counts[op] = counts.get(op, 0) + 1
    sys.stdout.write("gen32v: wrote %s, %d vectors\n" % (OUT, len(rows)))
    for op in OPS:
        sys.stdout.write("  %-5s %4d\n" % (op, counts.get(op, 0)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
