# -*- coding: utf-8 -*-
"""Generate C-04 compliant names for SoftFloat 3e's externals (D-113, D-114).

C-04 requires external names of at most eight characters, unique ignoring
case.  Release 3e contributes thirteen externals that break it, every one
truncating to `SOFTFLOA`.  The C-04 lint has reported them since it was
written and enforced on nothing, which is how the equivalent problem in
Release 2c got all the way to Assembler XF before anyone noticed (VL-25).

TWO KINDS OF NAME, AND WHY THEY NEED DIFFERENT TREATMENT
--------------------------------------------------------
VL-27.  Eight of the thirteen are ordinary identifiers and a plain
`#define` renames them.

The other five are written `#ifndef <name>` in both `include/primitives.h`
and their own `s_*.c`.  That is upstream's documented extension point:
defining the name as a macro says "this platform supplies the primitive",
and upstream then omits BOTH its declaration and its definition.  So a
`#define` that merely renames one of those five does not rename it, it
deletes it -- a primitive silently missing, which is the failure class
this project keeps having to close.

D-114 therefore uses the extension point as designed.  For those five the
macro expands to a call of an ONFLY-owned function, whose body
softfloat/derive3e.py copies mechanically from upstream's.  D-35 is the
precedent: ONFLY already owns a hand-derived roundPackToF64 and a
mechanically derived subMagsF64.

The prototypes below are not decoration.  Callers reach these functions
only through the macro, and without a declaration C89 would implicitly
declare them as returning int -- which for a function returning uint64_t
is a silently wrong value on every call.  <stdint.h> is included here
because this header is forced in ahead of everything else.

Output: generated/onf3enm.h.  Never edit by hand (IR-COM-01).

Run:  python tools/gen3enm.py [--check]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "generated", "onf3enm.h")

# Ordinary identifiers: a plain rename is safe.
PLAIN = [
    ("softfloat_addMagsF64", "SFADDM64"),
    ("softfloat_subMagsF64", "SFSUBM64"),
    ("softfloat_countLeadingZeros8", "SFCLZ8"),
    ("softfloat_normRoundPackToF64", "SFNRP64"),
    ("softfloat_normSubnormalF64Sig", "SFNSUB64"),
    ("softfloat_propagateNaNF64UI", "SFPNAN64"),
    ("softfloat_raiseFlags", "SFRAISE"),
    ("softfloat_roundPackToF64", "SFRP64"),
]

# Upstream feature-test macros.  (name, new name, return type, parameters)
# The parameter names here are the macro's, not the function's.
GUARDED = [
    ("softfloat_countLeadingZeros32", "SFCLZ32", "uint_fast8_t",
     [("a", "uint32_t a")]),
    ("softfloat_countLeadingZeros64", "SFCLZ64", "uint_fast8_t",
     [("a", "uint64_t a")]),
    ("softfloat_mul64To128M", "SFMUL128", "void",
     [("a", "uint64_t a"), ("b", "uint64_t b"), ("z", "uint32_t *zPtr")]),
    ("softfloat_shiftRightJam64", "SFSRJ64", "uint64_t",
     [("a", "uint64_t a"), ("dist", "uint_fast32_t dist")]),
    ("softfloat_shortShiftRightJam64", "SFSSRJ64", "uint64_t",
     [("a", "uint64_t a"), ("dist", "uint_fast8_t dist")]),
]


def verify():
    """C-04 by construction: at most 8 characters, unique ignoring case."""
    seen = {}
    for old, new in PLAIN + [(g[0], g[1]) for g in GUARDED]:
        if len(new) > 8:
            raise SystemExit("gen3enm: %r is %d characters, over C-04's 8"
                             % (new, len(new)))
        key = new.upper()
        if key in seen:
            raise SystemExit("gen3enm: %r and %r both give %r"
                             % (seen[key], old, new))
        seen[key] = old


BANNER = """\
/*
 * onf3enm.h - C-04 compliant names for SoftFloat 3e (D-113, D-114).
 *
 * GENERATED by tools/gen3enm.py.  Do not edit by hand (IR-COM-01).
 *
 * C-04 allows external names of at most eight characters, unique ignoring
 * case.  Release 3e has thirteen that break it and all thirteen truncate
 * to SOFTFLOA.  The file under third_party/ is untouched and stays
 * byte-identical to the released archive (D-28, D-35).
 *
 * Two groups, for the reason VL-27 records.  The first are ordinary
 * identifiers and are simply renamed.  The second are names upstream
 * tests with #ifndef -- defining one tells upstream the platform supplies
 * that primitive, and upstream then omits its declaration AND its
 * definition.  For those, ONFLY supplies the implementation:
 * softfloat/onfprim.c carries upstream's own body under the new name.
 *
 * The prototypes matter.  Callers reach these only through the macros, and
 * without a declaration C89 would implicitly declare them int -- silently
 * wrong for every one that returns uint64_t.
 */
#ifndef ONFLY_ONF3ENM_H
#define ONFLY_ONF3ENM_H

#include <stdint.h>
"""


def render():
    out = [BANNER, ""]
    out.append("/* Ordinary identifiers: renamed. */")
    width = max(len(o) for o, _ in PLAIN)
    for old, new in PLAIN:
        out.append("#define %-*s %s" % (width, old, new))
    out.append("")
    out.append("/* Upstream feature-test macros: ONFLY supplies these")
    out.append("   (softfloat/onfprim.c), so the macro is the extension")
    out.append("   point working as designed rather than a rename. */")
    for old, new, ret, params in GUARDED:
        decl = ", ".join(p[1] for p in params)
        out.append("%s %s(%s);" % (ret, new, decl))
        args = ", ".join(p[0] for p in params)
        call = ", ".join("(%s)" % p[0] for p in params)
        out.append("#define %s(%s) %s(%s)" % (old, args, new, call))
    out.append("")
    out.append("#endif /* ONFLY_ONF3ENM_H */")
    return "\n".join(out) + "\n"


def main(argv):
    verify()
    text = render()
    for n, line in enumerate(text.splitlines(), 1):
        if len(line) > 80:
            raise SystemExit("gen3enm: line %d is %d columns" % (n, len(line)))
    if "--check" in argv:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != text:
            sys.stderr.write("gen3enm: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("gen3enm: %s matches the generator, %d names\n"
                         % (OUT, len(PLAIN) + len(GUARDED)))
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(text)
    sys.stdout.write("gen3enm: wrote %s, %d renamed, %d ONFLY-supplied\n"
                     % (OUT, len(PLAIN), len(GUARDED)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
