# -*- coding: utf-8 -*-
"""Generate a small ONFNET image as a C array (D-121, D-122).

WHY THIS EXISTS
---------------
tests/tstdec.c and tests/tstgld.c both take a network *file*.  On MVS that
is a dead end until Gate G2: the transport that moves binary into TK5
without code-page translation, line-end insertion or trailing-blank
truncation has not been chosen, let alone proven (IR-TRN-01, IR-TRN-02).

So the decoder path -- header checks, payload CRC, big-endian load,
simulate, fingerprint -- could not run on MVS at all, which left FR-LOD-02
and IR-COM-05 completely unexercised there.

Embedding a small network as C source moves it through the same card
reader every other ONFLY source uses.  That is not a substitute for Gate
G2 and does not weaken it: what it proves is that the DECODER is correct
on a big-endian EBCDIC host, which is a different question from whether a
file can be moved onto one intact.

WHAT IS EMITTED
---------------
The bytes come from tests/run_dec.py's sample_network(), not from a second
description of a network written here.  run_dec.py already uses it for
TE-01..TE-08 on x86 and already has an oracle Network matching it, so
generating from it means the C side, the oracle and the x86 decode tests
cannot drift apart.

The image is a real ONFNET file: the full 164-byte header of SRS section
4.1, big-endian throughout, both CRCs computed by zlib (IR-NET-07), and
8-byte-aligned payload sections (IR-NET-05).  Nothing about it is
simplified for being small.

Output: generated/onfsynt.h.  Never edit by hand (IR-COM-01).

Run:  python tools/gensyn.py [--check]
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
for sub in ("tests", "layout", "generated", "oracle"):
    sys.path.insert(0, os.path.join(ROOT, sub))

import run_dec  # noqa: E402

OUT = os.path.join(ROOT, "generated", "onfsynt.h")

# Requests run against the embedded network.  Small enough that the whole
# job stays well inside a TK5 job step, varied enough to be worth running:
# rate 0 is ACC-2's exact silence, seed 0 is NR-13's remapping (golden
# request G-10's path), and 9999 Hz is NR-12's upper bound where the
# rejection path actually fires.
#
# (label, stimid, rate_hz, sim_ms, seed, rc)
REQUESTS = [
    ("S-01", 1,    0, 20,         1, 0),
    ("S-02", 1,   40, 20,         1, 0),
    ("S-03", 1,  200, 20,         1, 0),
    ("S-04", 1,  120, 20,         0, 0),
    ("S-05", 1, 9999, 10,         7, 0),
    ("S-06", 1,  200, 10, 999999999, 0),
]


def emit():
    data = run_dec.sample_network()
    a = run_dec._NET_ARGS

    w = io.StringIO()
    w.write("/*\n"
            " * onfsynt.h - ONFLY generated file - DO NOT EDIT.\n"
            " *\n"
            " * A complete ONFNET image (SRS section 4.1) as a C array, so that\n"
            " * the decoder, the kernel and the response fingerprint can be\n"
            " * exercised on a platform no network file has reached yet.\n"
            " *\n"
            " * Generated by tools/gensyn.py from tests/run_dec.py's\n"
            " * sample_network(), which is also what TE-01..TE-08 use on x86.\n"
            " * Edit the generator, not this file (IR-COM-01, D-18).\n"
            " */\n"
            "#ifndef ONFSYNT_H\n"
            "#define ONFSYNT_H\n"
            "\n"
            "#include \"onfplat.h\"\n"
            "\n")
    w.write("/* Header counts, so the driver can size its arrays statically\n"
            "   and a mismatch with the image is a compile error. */\n")
    w.write("#define ONFSYN_LEN %d\n" % len(data))
    w.write("#define ONFSYN_N %d\n" % a["n"])
    w.write("#define ONFSYN_E %d\n" % len(a["target"]))
    w.write("#define ONFSYN_NS %d\n" % len(a["stim"]))
    w.write("#define ONFSYN_NR %d\n" % len(a["readout"]))
    w.write("#define ONFSYN_DELAY %d\n" % a["delay"])
    w.write("\n")
    w.write("/* The requests tests/run_syn.py expects, in this order.\n"
            "   Each row is { stimid, rate_hz, sim_ms, seed }. */\n")
    w.write("#define ONFSYN_NREQ %d\n" % len(REQUESTS))
    w.write("static const onf_i32 onfsynr[ONFSYN_NREQ][4] = {\n")
    for _, sid, rate, ms, seed, _rc in REQUESTS:
        w.write("    { %dL, %dL, %dL, %dL },\n" % (sid, rate, ms, seed))
    w.write("};\n\n")
    w.write("static const onf_u8 onfsynt[ONFSYN_LEN] = {\n")
    # Eight bytes a line: four spaces of indent plus eight 8-character items
    # and their separators is 68 columns, comfortably inside the 80 the TK5
    # card reader truncates at, silently (D-93, VL-18).
    for i in range(0, len(data), 8):
        chunk = data[i:i + 8]
        w.write("    " + ", ".join("0x%02XU" % b for b in bytearray(chunk)))
        w.write(",\n" if i + 8 < len(data) else "\n")
    w.write("};\n\n#endif /* ONFSYNT_H */\n")
    return w.getvalue()


def main(argv):
    want = emit()
    if "--check" in argv:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != want:
            sys.stderr.write("gensyn: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("gensyn: %s matches the generator\n" % OUT)
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(want)
    sys.stdout.write("gensyn: wrote %s, %d bytes of network in %d lines\n"
                     % (OUT, len(run_dec.sample_network()),
                        want.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
