# -*- coding: utf-8 -*-
"""Ship a TestFloat vector table to MVS for TT-02 (D-112, D-115).

NR-14 requires the TestFloat vector suite for the used operations to pass
on every compiler and platform.  On x86 that is `make tt02`, which pipes
testfloat_gen straight into the driver -- 260,376 cases.  MVS cannot do
that: testfloat_gen is a modern C program with no MVS build, and there is
no pipe to feed it through anyway.

So the vectors are generated here and shipped as a table, the same way
generated/onf2cv.h already reaches MVS.  Two things follow from that and
both are stated rather than glossed:

  * A table is a SAMPLE.  It cannot be the live stream, so the MVS run
    covers fewer cases than the x86 run and TT-02 on MVS means something
    weaker than TT-02 on x86.  How much weaker is the size, which D-115
    settles by measurement rather than by choosing a number.

  * The sample is STRATIFIED, not the first N.  testfloat_gen emits its
    cases in a deliberate order -- zeros, subnormals, boundaries,
    rounding ties, then bulk patterns -- so taking a prefix would take
    mostly one kind of case.  Every k-th case is taken instead, across
    the whole stream, so the sample spans the classes upstream built in.

NaN cases are excluded exactly as tstflt.c excludes them, for the reason
VL-11 records: the reference is built against the 8086 specialization
while ONFLY uses ARM-VFPv2 default NaN, so a NaN case would report a
difference that is by design.  FR-SIM-08 aborts on NaN before the engine
could ever reach one.

Values are emitted as 32-bit pattern pairs, never decimal text (NR-06),
which is also the shape SoftFloat 2c's float64 has -- so nothing here
needs a 64-bit integer type (NR-04).

Output: generated/onftfv.h.  Never edit by hand (IR-COM-01).

Run:  python tools/gentf2.py --gen <testfloat_gen> [--per-op N] [--check]
"""
import io
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "generated", "onftfv.h")

OPS = [("ADD", "f64_add"), ("SUB", "f64_sub"), ("MUL", "f64_mul"),
       ("LT", "f64_lt"), ("LE", "f64_le"), ("EQ", "f64_eq")]

DEFAULT_PER_OP = 2000


def is_nan(hi, lo):
    return (hi & 0x7FF00000) == 0x7FF00000 and ((hi & 0x000FFFFF) or lo)


def cases(gen, full):
    """Every usable case testfloat_gen emits for one operation."""
    p = subprocess.Popen([gen, "-rnear_even", "-level", "1", full],
                         stdout=subprocess.PIPE,
                         stderr=open(os.devnull, "wb"))
    out, _ = p.communicate()
    rows = []
    compare = full in ("f64_lt", "f64_le", "f64_eq")
    for line in out.decode("ascii", "replace").splitlines():
        if len(line) < 36:
            continue
        ahi, alo = int(line[0:8], 16), int(line[8:16], 16)
        bhi, blo = int(line[17:25], 16), int(line[25:33], 16)
        if is_nan(ahi, alo) or is_nan(bhi, blo):
            continue
        if compare:
            rhi, rlo = 0, 1 if line[34] == "1" else 0
        else:
            rhi, rlo = int(line[34:42], 16), int(line[42:50], 16)
            if is_nan(rhi, rlo):
                continue
        rows.append((ahi, alo, bhi, blo, rhi, rlo))
    return rows


def sample(rows, want):
    """Every k-th case, so the sample spans the stream rather than its head."""
    if want >= len(rows):
        return rows, len(rows)
    step = len(rows) / float(want)
    picked = []
    i = 0.0
    while len(picked) < want and int(i) < len(rows):
        picked.append(rows[int(i)])
        i += step
    return picked, len(rows)


BANNER = """\
/*
 * onftfv.h - Berkeley TestFloat vectors for TT-02 on MVS (D-112, D-115).
 *
 * GENERATED by tools/gentf2.py.  Do not edit by hand (IR-COM-01).
 *
 * A SAMPLE of the x86 TT-02 stream, not the whole of it: testfloat_gen
 * has no MVS build and there is no pipe to feed it through, so the cases
 * are shipped as a table.  TT-02 on MVS therefore means something weaker
 * than TT-02 on x86, and the counts below say exactly how much weaker.
 *
 * Every k-th case is taken rather than the first N, because
 * testfloat_gen emits its cases in a deliberate order and a prefix would
 * be mostly one kind of case.
 *
 * NaN cases are excluded (VL-11, D-46): the reference is built against
 * the 8086 specialization while ONFLY uses ARM-VFPv2 default NaN.
 *
 * 32-bit pattern pairs, never decimal text (NR-06); no 64-bit integer
 * type appears (NR-04).
 */
#ifndef ONFLY_ONFTFV_H
#define ONFLY_ONFTFV_H

#define ONFTF_ADD 0
#define ONFTF_SUB 1
#define ONFTF_MUL 2
#define ONFTF_LT  3
#define ONFTF_LE  4
#define ONFTF_EQ  5

struct onftfv {
    int op;
    unsigned long ahi;
    unsigned long alo;
    unsigned long bhi;
    unsigned long blo;
    unsigned long rhi;
    unsigned long rlo;
};
"""


def render(rows, notes):
    out = [BANNER, ""]
    for n in notes:
        out.append("/* %s */" % n)
    out.append("#define ONFTF_NVEC %d" % len(rows))
    out.append("")
    out.append("static const struct onftfv onftfvec[ONFTF_NVEC] = {")
    for op, ahi, alo, bhi, blo, rhi, rlo in rows:
        out.append("    { ONFTF_%-3s 0x%08lXUL, 0x%08lXUL,"
                   % (op + ",", ahi, alo))
        out.append("      0x%08lXUL, 0x%08lXUL, 0x%08lXUL, 0x%08lXUL },"
                   % (bhi, blo, rhi, rlo))
    out.append("};")
    out.append("")
    out.append("#endif /* ONFLY_ONFTFV_H */")
    return "\n".join(out) + "\n"


def main(argv):
    gen = None
    per_op = DEFAULT_PER_OP
    for i, a in enumerate(argv):
        if a == "--gen" and i + 1 < len(argv):
            gen = argv[i + 1]
        if a == "--per-op" and i + 1 < len(argv):
            per_op = int(argv[i + 1])
    check = "--check" in argv

    if gen is None:
        gen = os.path.join(ROOT, "third_party", "TestFloat-3e", "build",
                           "Win32-MinGW", "testfloat_gen.exe")
    if not os.path.exists(gen):
        sys.stderr.write("gentf2: testfloat_gen not found: %s\n"
                         "Build it with:  make testfloat\n" % gen)
        return 2

    rows = []
    notes = []
    for tag, full in OPS:
        avail = cases(gen, full)
        picked, total = sample(avail, per_op)
        notes.append("%-3s %6d of %6d usable cases" % (tag, len(picked),
                                                       total))
        for r in picked:
            rows.append((tag,) + r)
    notes.append("%d vectors, %d per operation requested"
                 % (len(rows), per_op))

    text = render(rows, notes)
    for n, line in enumerate(text.splitlines(), 1):
        if len(line) > 80:
            raise SystemExit("gentf2: line %d is %d columns" % (n, len(line)))
    if check:
        have = (io.open(OUT, encoding="ascii").read()
                if os.path.exists(OUT) else None)
        if have != text:
            sys.stderr.write("gentf2: %s is stale or edited by hand\n" % OUT)
            return 1
        sys.stdout.write("gentf2: %s matches the generator, %d vectors\n"
                         % (OUT, len(rows)))
        return 0
    io.open(OUT, "w", encoding="ascii", newline="\n").write(text)
    sys.stdout.write("gentf2: wrote %s\n" % OUT)
    for n in notes:
        sys.stdout.write("  %s\n" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
